title: Booze Blog
description: A blog about alcohol brands and fonts.
header_text: ""
footer_text: Copyright 2020 Booze Blog
header_feature_image: ../uploads/website-heading-300x.png
bannerheight: 20vmax
logo: ../uploads/logos-300x.png
favicon: ../uploads/android-chrome-512x512.png
gridlayout: false
fixednavbar: false
upzoom: true
