title: Booze Blog
description: A blog about alcohol brands and fonts.
header_text: ""
footer_text: Copyright 2020 Booze Blog
header_feature_image: ../uploads/website-heading.jpg
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
