title: Your name or name of site
description: A website with a blog
header_text: My Dream Blog
footer_text: Copyright 2020 Your name
header_feature_image: ../uploads/artboard-1-72x-100.jpg
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
